### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by McDunkinY** [maurits150/simploo#2]
Can you provide an example of class inheritance ( if possible )

I currently have a PhysicsBody class and I have another Wheel class which I need for it to inherit from PhysicsBody.

I'm using the traditional syntax without any namespaces.

```
class "PhysicsBody" {
    ....
}

class "Wheel" {
    ...
}
```

**Comment by Benjiko99** [comment]
Get outa hea!

**Comment by McDunkinY** [comment]
Fixed. Did some snooping around in the source, found out it's "extends"

**Comment by maurits150** [comment]
You may want to check out https://github.com/maurits150/simploo/wiki/1.0-%7C-Wiki-Backup
The 1.0 wiki backup is pretty complete on its own and should be able to help you to get started.
