### ISSUE TITLE
default (nil) values not working ?

### ISSUE THREAD

**Issue by gcmartijn** [maurits150/simploo#9]
Hi

I am trying out some things with namespaces and classes and I now come across the following 'problem'. Is this a desired result?

Sometimes I already set some default values, but I don't think it's possible to use a nil value in a table in lua. That is why the error below goes I guess.

```
class "Frameset" {
    private {
        name = nil -- point 1
        -- name = "" -- point 2 this is the fix (not using a nil value, but a empty string value "")
    },
    public {
    	__construct = function(self, name)
            self.name = name -- not working
            -- self:setName(name) -- not working
            print(self.name) -- nil
            print(name) -- hoi
        end,
        setName = function(self, name)
            self.name = name
        end,
        getName = function(self)
            return self.name
        end
    }
}

test = Frameset.new("hoi")
print(test:getName()) -- nil - because i'm using point 1 above
```

**Comment by mi1agency** [comment]
Simploo provides an exposed global called 'null' for this which is just a fancy string that holds the place when you just want to reserve a key with no specific value until set because otherwise the key is garbage collected automatically.

ex:
name = null

**Comment by maurits150** [comment]
Yeah the 'null' variable can be used for this. See https://github.com/maurits150/simploo/wiki/Syntax-Reference

I'm sorry for not noticing this issue earlier.

Apparently I don't get any email notifications for new issues despite 'watching' the repository.
